apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../manager
patches:
  - target:
      kind: Deployment
      name: moneypod-app
    patch: |-
      - op: test
        path: /spec/template/spec/containers/0/args/4
        value: --zap-devel=false
      - op: replace
        path: /spec/template/spec/containers/0/args/4
        value: --zap-devel=true
      - op: test
        path: /spec/template/spec/containers/0/args/5
        value: --zap-log-level=info
      - op: replace
        path: /spec/template/spec/containers/0/args/5
        value: --zap-log-level=3
  - target:
      kind: Service
      name: moneypod-metrics
    patch: |-
      - op: add
        path: /spec/type
        value: NodePort
      - op: test
        path: /spec/ports/0/name
        value: metrics
      - op: add
        path: /spec/ports/0/nodePort
        value: 30000
  - target:
      kind: NetworkPolicy
      name: moneypod-allow-metrics
    patch: |-
      - op: add
        path: /spec/ingress/0/from/-
        value:
          ipBlock:
            cidr: 0.0.0.0/0
