apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bootstrap
  - flux.yaml
  - https://github.com/cert-manager/cert-manager/releases/latest/download/cert-manager.yaml
  - https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
  - victoria-metrics

patches:
  - target:
      kind: Deployment
      name: metrics-server
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --kubelet-insecure-tls
