apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: victoria-metrics
  namespace: default
spec:
  interval: 1h
  provider: generic
  url: https://victoriametrics.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics
  namespace: default
spec:
  releaseName: victoria-metrics
  interval: 1h
  timeout: 5m
  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: victoria-metrics
      version: <1.0.0
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    nameOverride: victoria-metrics
    fullnameOverride: victoria-metrics
    alertmanager:
      enabled: true
    defaultDashboardsEnabled: false
    defaultRules:
      create: false
    experimentalDashboardsEnabled: false
    grafana:
      enabled: true
      adminPassword: admin
      serviceMonitor:
        enabled: false
      service:
        type: NodePort
        nodePort: 30003
    kubeControllerManager:
      enabled: false
    kubeEtcd:
      enabled: false
    kubeScheduler:
      enabled: false
    prometheus-node-exporter:
      enabled: false
    victoria-metrics-operator:
      admissionWebhooks:
        certManager:
          enabled: true
        enabled: true
      operator:
        disable_prometheus_converter: false
        enable_converter_ownership: true
        useCustomConfigReloader: true
      serviceMonitor:
        enabled: false
    vmalert:
      enabled: true
    vmsingle:
      enabled: true
      spec:
        retentionPeriod: 1d
        storage:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
