#  ┬─┐┬─┐┬─┐  ┌─┐┌─┐┌┌┐┌┌┐o┌┐┐
#  │─┘│┬┘├─ ──│  │ ││││││││ │
#  ┘  ┘└┘┴─┘  └─┘┘─┘┘ ┘┘ ┘┘ ┘

repos:
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.28.0
    hooks:
      - id: gitleaks
        args:
          - --config=gitleaks.toml
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
  - repo: local
    hooks:
      - id: regenerate-manifests
        name: Regenerate manifests
        entry: task -d src generate:all
        language: system
        files: src/.+
        types: [file]
        pass_filenames: false
