apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus
spec:
  interval: 1h
  provider: generic
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
spec:
  releaseName: prometheus
  interval: 1h
  timeout: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus
      version: <78.0.0
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    nameOverride: prometheus
    fullnameOverride: prometheus
    grafana:
      enabled: true
      adminPassword: admin
      serviceMonitor:
        enabled: false
      service:
        type: NodePort
        nodePort: 30001
      dashboardProviders:
        moneypod.yaml:
          apiVersion: 1
          providers:
            - name: moneypod
              orgId: 1
              folder: MoneyPod
              type: file
              disableDeletion: false
              editable: true
              options:
                path: /var/lib/grafana/dashboards/moneypod
      dashboardsConfigMaps:
        moneypod: moneypod-dashboards
    kubeControllerManager:
      enabled: false
    kubeEtcd:
      enabled: false
    kubeScheduler:
      enabled: false
    prometheus-node-exporter:
      enabled: false
    prometheus-operator:
      admissionWebhooks:
        certManager:
          enabled: true
        enabled: true
      operator:
        disable_prometheus_converter: false
        enable_converter_ownership: true
        useCustomConfigReloader: true
      serviceMonitor:
        enabled: false
    prometheus:
      enabled: true
      prometheusSpec:
        retention: 1d
        ruleSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
        probeSelectorNilUsesHelmValues: false
        scrapeConfigSelectorNilUsesHelmValues: false
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 1Gi
