{
 "title": "MoneyPod - Topk",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_created,namespace)"
    }
   },
   {
    "name": "owner_kind",
    "label": "Owner Kind",
    "query": {
     "query": "label_values(moneypod:pod_requests_total_cost{namespace=~\"$namespace\"},owner_kind)"
    }
   },
   {
    "name": "owner_name",
    "label": "Owner Name",
    "query": {
     "query": "label_values(moneypod:pod_requests_total_cost{namespace=~\"$namespace\", owner_kind=~\"$owner_kind\"},owner_name)"
    }
   },
   { "name": "topk", "label": "Topk", "query": "2,5,10,15,30,50" }
  ]
 },
 "panels": [
  {
   "title": "Node Cost by Node",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk($topk,\n    sum by (node) (\n        moneypod:node_total_cost\n    )\n) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Cost by Role",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk($topk,\n    sum by (role) (\n        sum by (node) (\n            moneypod:node_total_cost\n        )\n        * on (node) group_left (role)\n        kube_node_role\n    )\n) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Namespace Cost",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk($topk,\n    sum by (namespace) (\n        moneypod:pod_effective_total_cost{namespace=~\"$namespace\", owner_kind=~\"$owner_kind\", owner_name=~\"$owner_name\"}\n    )\n) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Namespace Cost Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "topk($topk,\n    rate(\n        sum by (namespace) (\n            moneypod:pod_effective_total_cost{namespace=~\"$namespace\", owner_kind=~\"$owner_kind\", owner_name=~\"$owner_name\"}\n        ) [$__rate_interval]\n    )\n) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application Cost",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk($topk,\n    sum by (owner_kind, owner_name) (\n        moneypod:pod_effective_total_cost{namespace=~\"$namespace\", owner_kind=~\"$owner_kind\", owner_name=~\"$owner_name\"}\n    )\n) > 0",
     "legendFormat": "{{owner_kind}}/{{owner_name}}"
    }
   ]
  },
  {
   "title": "Application Cost Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "topk($topk,\n    rate(\n        sum by (owner_kind, owner_name) (\n            moneypod:pod_effective_total_cost{namespace=~\"$namespace\", owner_kind=~\"$owner_kind\", owner_name=~\"$owner_name\"}\n        ) [$__rate_interval]\n    )\n) > 0",
     "legendFormat": "{{owner_kind}}/{{owner_name}}"
    }
   ]
  }
 ]
}