nameReference:
  - kind: Issuer
    fieldSpecs:
      - kind: Certificate
        path: /spec/issuerRef/name
  - kind: Certificate
    fieldSpecs:
      - kind: Certificate
        path: /spec/secretName
      - kind: Deployment
        path: /spec/template/spec/volumes/secret/secretName
