# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metrics
spec:
  endpoints:
    - path: /metrics
      port: metrics
      scheme: https
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        serverName: SERVICE.NAMESPACE.svc
        insecureSkipVerify: false
        ca:
          secret:
            name: metrics
            key: ca.crt
        cert:
          secret:
            name: metrics
            key: tls.crt
        keySecret:
          name: metrics
          key: tls.key
