apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: app
subjects:
  - kind: ServiceAccount
    name: app
