{
 "title": "MoneyPod",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(moneypod_node_hourly_cost,cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(moneypod_pod_requests_hourly_cost{cluster=~\"$cluster\"},namespace)"
    }
   },
   {
    "name": "owner_kind",
    "label": "Owner Kind",
    "query": {
     "query": "label_values(moneypod:pod_requests_total_cost{cluster=~\"$cluster\", namespace=~\"$namespace\"},owner_kind)"
    }
   },
   {
    "name": "owner_name",
    "label": "Owner Name",
    "query": {
     "query": "label_values(moneypod:pod_requests_total_cost{cluster=~\"$cluster\", namespace=~\"$namespace\", owner_kind=~\"$owner_kind\"},owner_name)"
    }
   },
   { "name": "topk", "label": "Topk", "query": "2,5,10,15,30,50" },
   {
    "name": "min_step",
    "label": "Min Step",
    "query": "15s,30s,1m,2m,5m,10m,15m,30m,1h,2h,3h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Node Cost by Node",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk($topk,\n    sum by (node) (\n        moneypod:node_total_cost{cluster=~\"$cluster\"}\n    )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Cost by Role",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk($topk,\n    sum by (role) (\n        sum by (node) (\n            moneypod:node_total_cost{cluster=~\"$cluster\"}\n        )\n        * on (node) group_left (role)\n        kube_node_role{cluster=~\"$cluster\"}\n    )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Namespace Cost",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk($topk,\n    sum by (namespace) (\n        moneypod:pod_effective_total_cost{cluster=~\"$cluster\", namespace=~\"$namespace\", owner_kind=~\"$owner_kind\", owner_name=~\"$owner_name\"}\n    )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Namespace Cost Rate",
   "type": "timeseries",
   "description": "Namespace cost per second",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "topk($topk,\n    rate(\n        sum by (namespace) (\n            moneypod:pod_effective_total_cost{cluster=~\"$cluster\", namespace=~\"$namespace\", owner_kind=~\"$owner_kind\", owner_name=~\"$owner_name\"}\n        ) [$__rate_interval]\n    )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application Cost",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk($topk,\n    sum by (owner_kind, owner_name) (\n        moneypod:pod_effective_total_cost{cluster=~\"$cluster\", namespace=~\"$namespace\", owner_kind=~\"$owner_kind\", owner_name=~\"$owner_name\"}\n    )\n)",
     "legendFormat": "{{owner_kind}}/{{owner_name}}"
    }
   ]
  },
  {
   "title": "Application Cost Rate",
   "type": "timeseries",
   "description": "Application cost per second",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "topk($topk,\n    rate(\n        sum by (owner_kind, owner_name) (\n            moneypod:pod_effective_total_cost{cluster=~\"$cluster\", namespace=~\"$namespace\", owner_kind=~\"$owner_kind\", owner_name=~\"$owner_name\"}\n        ) [$__rate_interval]\n    )\n)",
     "legendFormat": "{{owner_kind}}/{{owner_name}}"
    }
   ]
  },
  {
   "title": "Application requests too big",
   "type": "timeseries",
   "description": "Closer to 100% is better. X percent means that we pay for requested resources, but usage cost is only X of that resources price.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bottomk($topk,\n    sum by (owner_kind, owner_name) (\n        moneypod:pod_usage_total_cost{namespace=~\"$namespace\", owner_kind=~\"$owner_kind\", owner_name=~\"$owner_name\"}\n        / on (cluster, namespace, pod) group_left (owner_kind, owner_name)\n        (moneypod:pod_requests_total_cost{cluster=~\"$cluster\", namespace=~\"$namespace\", owner_kind!=\"Node\"} > 0)\n    ) < 1\n)",
     "legendFormat": "{{owner_kind}}/{{owner_name}}"
    }
   ]
  },
  {
   "title": "Underutilized nodes",
   "type": "timeseries",
   "description": "Closer to 100% is better. X percent means that we use only X percent of the node.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bottomk($topk,\n    (\n        sum by (cluster, node) (moneypod:pod_usage_total_cost{cluster=~\"$cluster\", namespace=~\"$namespace\", owner_kind=~\"$owner_kind\", owner_name=~\"$owner_name\"})\n        / on (cluster, node) (moneypod:node_total_cost{cluster=~\"$cluster\"})\n    ) < 1\n)",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}