commonLabels:
  - kind: ServiceMonitor
    path: /spec/selector/matchLabels
    create: true
nameReference:
  - kind: Certificate
    fieldSpecs:
      - kind: ServiceMonitor
        path: /spec/endpoints/tlsConfig/ca/secret/name
      - kind: ServiceMonitor
        path: /spec/endpoints/tlsConfig/cert/secret/name
      - kind: ServiceMonitor
        path: /spec/endpoints/tlsConfig/keySecret/name
