name: Build

on:
  workflow_call:
    inputs:
      runs-on:
        required: true
        type: string
        description: Runner name for the build job
      platform:
        required: true
        type: string
        description: Build platform name
      image:
        required: true
        type: string
        description: Docker repository image
      meta-labels:
        required: true
        type: string
        description: Docker meta labels

jobs:
  build:
    name: Build
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Prepare
        run: echo "PLATFORM_PAIR=${PLATFORM//\//-}" >> $GITHUB_ENV
        env:
          PLATFORM: ${{ inputs.platform }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v5
        with:
          context: src
          platforms: ${{ inputs.platform }}
          labels: ${{ inputs.meta-labels }}
          cache-from: type=registry,ref=${{ inputs.image }}:latest
          cache-to: type=inline
          outputs: |-
            type=image,name=${{ inputs.image }},push-by-digest=true,name-canonical=true,push=true

      - name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ env.PLATFORM_PAIR }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1
