name: Image

on:
  push:
    # branches:
    #   - "**"
    # paths:
    #   - src/**/*
    # tags:
    #   - v*
  pull_request:
    branches:
      - main

env:
  REGISTRY_IMAGE: ghcr.io/${{ github.repository }}
  META_TAGS: |
    type=raw,value=latest,enable={{is_default_branch}}
    type=semver,pattern={{version}}
    type=semver,pattern={{major}}.{{minor}}
    type=semver,pattern={{major}}
    type=ref,event=branch
    type=ref,event=pr
    type=sha

permissions: &permissions
  packages: write
  contents: read

jobs:
  build:
    name: Build
    permissions: *permissions
    uses: ./.github/workflows/build.yaml
    secrets: inherit
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            runs-on: ubuntu-latest
          - site: linux/arm64
            runs-on: moneypod-cosmos-arm64
    with:
      platform: ${{ matrix.platform }}
      runs-on: ${{ matrix.runs-on }}

  merge:
    name: Merge manifest
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.sha }}-merge
      cancel-in-progress: false
    needs: [build]
    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: /tmp/digests
          pattern: digests-*
          merge-multiple: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: ${{ env.META_TAGS }}

      - name: Create manifest list and push
        working-directory: /tmp/digests
        run: |
          printf '${{ env.REGISTRY_IMAGE }}@sha256:%s ' * | \
          xargs docker buildx imagetools create $(jq -Mcr '.tags | map("-t " + .) | join(" ")' <<< "${DOCKER_METADATA_OUTPUT_JSON}")

      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ env.REGISTRY_IMAGE }}:${{ steps.meta.outputs.version }}
