name: Image

on:
  push:
    branches:
      - "**"
    paths:
      - src/**/*
      - .github/workflows/image.yaml
    tags:
      - v*
  pull_request:
    branches:
      - main

permissions: &permissions
  packages: write
  contents: read

env:
  IMAGE: &image ghcr.io/${{ github.repository }}
  META_TAGS: &metaTags |
    type=raw,value=latest,enable={{is_default_branch}}
    type=semver,pattern={{version}}
    type=semver,pattern={{major}}.{{minor}}
    type=semver,pattern={{major}}
    type=ref,event=branch
    type=ref,event=pr
    type=sha

jobs:
  meta:
    name: Generate metadata
    runs-on: ubuntu-latest
    outputs:
      labels: ${{ steps.meta.outputs.labels }}
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: *image
          tags: *metaTags

  build:
    name: Build
    permissions: *permissions
    uses: ./.github/workflows/build.yaml
    needs: [meta]
    secrets: inherit
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            runs-on: ubuntu-24.04
          - platform: linux/arm64
            runs-on: ubuntu-24.04-arm
    concurrency:
      group: ${{ github.workflow }}-${{ github.sha }}-${{ matrix.platform }}-build
      cancel-in-progress: false
    with:
      platform: ${{ matrix.platform }}
      runs-on: ${{ matrix.runs-on }}
      image: *image
      meta-labels: ${{ needs.meta.outputs.labels }}

  merge:
    name: Merge manifest
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.sha }}-merge
      cancel-in-progress: false
    needs: [build]
    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: /tmp/digests
          pattern: digests-*
          merge-multiple: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE }}
          tags: ${{ env.META_TAGS }}

      - name: Create manifest list and push
        working-directory: /tmp/digests
        run: |
          printf '${{ env.IMAGE }}@sha256:%s ' * | \
          xargs docker buildx imagetools create $(jq -Mcr '.tags | map("-t " + .) | join(" ")' <<< "${DOCKER_METADATA_OUTPUT_JSON}")

      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ env.IMAGE }}:${{ steps.meta.outputs.version }}
