#  ┬─┐┬─┐┬  ┬─┐┬─┐┐─┐┬─┐
#  │┬┘├─ │  ├─ │─┤└─┐├─
#  ┘└┘┴─┘┘─┘┴─┘┘ ┘──┘┴─┘

name: Release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5

      - name: Install Task
        uses: go-task/setup-task@v1

      - name: Remove 'v' from tag
        id: version
        run: echo "${{ github.ref_name }}" | sed -r 's/^v//' |
          xargs printf "version=%s" | tee -a "$GITHUB_OUTPUT"

      - name: Kustomize Build
        run: task generate:distribute "image=ghcr.io/${{ github.repository }}:${{ steps.version.outputs.version }}"
        working-directory: src

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: install.yaml
