name: E2E Tests

on:
  push:
    paths:
      - src/**/*
      - .github/workflows/test-e2e.yaml
  pull_request:

jobs:
  test-e2e:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: src/go.mod
          cache-dependency-path: src/go.sum

      - name: Install Task
        uses: go-task/setup-task@v1

      - name: Go mod tidy
        run: go mod tidy
        working-directory: src

      - name: Running Test e2e
        run: task test:e2e
        working-directory: src
